version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: strong-password
    ports:
      - "127.0.0.1:3306:3306"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: strong-password
      POSTGRES_DB: blindhackerdb
    ports:
      - "127.0.0.1:5432:5432"
    restart: always

  php:
    build: ./php
    ports:
    - "127.0.0.1:80:80"
    restart: always
    links:
      - "mysql:mysql_net"
      - "postgres:postgresql_net"

  flask:
    build: ./flask
    ports:
    - "127.0.0.1:8080:8080"
    restart: always
    links:
      - "mysql:mysql_net"
      - "postgres:postgresql_net"

  tg_bot_browser:
    build: ./tg_bot_browser
    restart: always
    links:
      - "php:blind_hacker"
      - "flask:blind_hacker_forum"

